version: '{build}'
build_script:
  - ps: |
      .\.paket\paket.bootstrapper.exe
      .\.paket\paket.exe restore
      .\build.cmd nuget
      if ($lastexitcode -ne 0){ exit $lastexitcode }
test: off
artifacts:
  - path: bin\*.nupkg
